### ISSUE TITLE
Revisions requested by BHS (EG)

### ISSUE THREAD

**Issue by coregis** [eldang/ballard-4culture#16]
- [x] Force pop-up to close when someone chooses a name from the drop-down
- [x] Make "Zoom to all of Ballard" link also clear the search
- [x] Investigate options to prevent pop-ups from obscuring map points (possibly make it a movable object)
- [x] Make active pop-up tab show the person that is selected from the drop-down menu when the points are filtered

**Comment by eldang** [comment]
I've reordered these from most self-contained to most open-ended.  The first should be easy, the second can be done by using jQuery UI's own popups (click on the map at http://terramgn.terragis.net/ol6/baseviewer/map.html to see one in action), and the third could potentially be a bit of a rabbit hole so I definitely want to address the other two before it.

**Comment by eldang** [comment]
Comment above needs renumbering because we added an item.  So:

* Force popup to close: should be easy
* Zoom to all link: definitely easy
* jQuery UI popups: moderate complexity, but a known quantity
* Making the active popup tab show the right person: bigger unknown than the others.

**Comment by eldang** [comment]
After working on https://github.com/eldang/ballard-4culture/pull/21 I think I can see how to select the right tab, but I'll come back to that tomorrow or on Monday.
