### ISSUE TITLE
Housekeeping for original repo?

### ISSUE THREAD

**Issue by coregis** [eldang/ballard-4culture#2]
Thanks for setting this up and adding me @eldang ! What would you consider the best practice for tidying up the original repo on my Github account? Can I nuke it without adversely affecting your fork? At the moment I cannot open in Github Desktop because my local repo has the same name as your fork. Please advise :)

**Comment by eldang** [comment]
@coregis I'm reasonably confident that you can nuke it without harming my fork, and it's worth trying now while I have a local copy of everything that I could make a fresh repository from in case it does cause a problem.
